version: "3"
services:
    redis-cluster-7006:
        image: redis
        container_name: node-7006
        ports:
            - "7006:6379"
        volumes:
            - ./7006/redis.conf:/usr/local/etc/redis/redis.conf
            - ./7006/log:/var/log/redis
            - ./7006/data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf --sentinel"

    redis-cluster-7007:
        image: redis
        container_name: node-7007
        ports:
            - "7007:6379"
        volumes:
            - ./7007/redis.conf:/usr/local/etc/redis/redis.conf
            - ./7007/log:/var/log/redis
            - ./7007/data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf --sentinel"

networks:
    redis-cluster_frontend:
        ipam:
            config:
            - subnet: 172.18.0.0/16
